[package]
name = "proto-core"
version = "0.0.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
tokio = { workspace = true }
bincode = { workspace = true }
paste = { workspace = true }

[lints]
workspace = true
